const DB={get(k,d){let x=localStorage.getItem('sst_'+k);if(x)return JSON.parse(x);localStorage.setItem('sst_'+k,JSON.stringify(d));return d},set(k,v){localStorage.setItem('sst_'+k,JSON.stringify(v))}};
const profile={name:'Tanvi',id:'IT2024XXX',email:'tanvi@example.com',phone:'+91 98765 43210',department:'Information Technology',college:'ABC College of Engineering',semester:3,cgpa:'8.6'};
const defaultSkills=[['HTML','Web Development','Advanced',90,1,'Verified'],['CSS','Web Development','Intermediate',75,1,'Verified'],['JavaScript','Web Development','Intermediate',70,2,'Verified'],['Java','Programming','Beginner',40,3,'Pending'],['Python','Programming','Intermediate',65,2,'Verified'],['SQL','Database','Intermediate',60,2,'Verified'],['PostgreSQL','Database','Beginner',45,3,'Pending'],['Git','Other','Beginner',35,3,'Pending']].map((x,i)=>({id:i+1,name:x[0],category:x[1],level:x[2],progress:x[3],semester:x[4],status:x[5]}));
const defaultProjects=[{title:'Student Skill Tracking System',description:'Semester-wise skill tracking and faculty verification project.',tech:'HTML, CSS, JavaScript, Spring Boot, PostgreSQL',semester:3,github:'#',status:'In Progress',verification:'Pending'},{title:'Electricity Billing System',description:'Java JDBC billing application.',tech:'Java, JDBC, PostgreSQL',semester:3,github:'#',status:'Completed',verification:'Verified'}];
function init(){DB.get('profile',profile);DB.get('skills',defaultSkills);DB.get('projects',defaultProjects);const p=DB.get('profile',profile);document.querySelectorAll('[data-name]').forEach(e=>e.textContent=p.name);document.querySelectorAll('[data-avatar]').forEach(e=>e.textContent=p.name[0]);const s=document.querySelector('#sidebar'),m=document.querySelector('#menu');if(s&&m)m.onclick=()=>s.classList.toggle('open');document.querySelectorAll('.side-link').forEach(a=>{if(a.href===location.href)a.classList.add('active')})}
function toast(x){const t=document.querySelector('#toast');if(!t)return;t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}function openModal(id){document.getElementById(id)?.classList.add('show')}function closeModal(id){document.getElementById(id)?.classList.remove('show')}function logout(){localStorage.removeItem('loggedIn');location.href='../login.html'}
function skillsPage(){const box=document.querySelector('#skillsRows');if(!box)return;const a=DB.get('skills',defaultSkills);box.innerHTML=a.map((s,i)=>`<tr><td><b>${s.name}</b></td><td>${s.category}</td><td>${s.level}</td><td><div class="progress"><span style="width:${s.progress}%"></span></div>${s.progress}%</td><td>${s.semester}</td><td><span class="badge ${s.status==='Verified'?'success':'warning'}">${s.status}</span></td></tr>`).join('')}
function addSkill(e){e.preventDefault();let a=DB.get('skills',defaultSkills);a.push({id:Date.now(),name:skillName.value,category:skillCategory.value,level:skillLevel.value,progress:+skillProgress.value||10,semester:+skillSemester.value,status:'Pending'});DB.set('skills',a);closeModal('skillModal');skillsPage();toast('Skill added successfully')}
function projectsPage(){const box=document.querySelector('#projectRows');if(!box)return;box.innerHTML=DB.get('projects',defaultProjects).map(p=>`<tr><td><b>${p.title}</b><br><small>${p.description}</small></td><td>${p.tech}</td><td>${p.semester}</td><td>${p.status}</td><td><span class="badge ${p.verification==='Verified'?'success':'warning'}">${p.verification}</span></td></tr>`).join('')}
function addProject(e){e.preventDefault();let a=DB.get('projects',defaultProjects);a.push({title:projectTitle.value,description:projectDescription.value,tech:projectTech.value,semester:+projectSemester.value,github:projectGithub.value||'#',status:'In Progress',verification:'Pending'});DB.set('projects',a);closeModal('projectModal');projectsPage();toast('Project added successfully')}
function profilePage(){const p=DB.get('profile',profile);document.querySelectorAll('[data-profile]').forEach(e=>e.value=p[e.dataset.profile]||'');const f=document.querySelector('#profileForm');if(f)f.onsubmit=e=>{e.preventDefault();const n={...p};document.querySelectorAll('[data-profile]').forEach(x=>n[x.dataset.profile]=x.value);DB.set('profile',n);toast('Profile updated')};}
function semesterPage(){const box=document.querySelector('#semesterRows');if(!box)return;const a=[{s:1,k:4,v:3,p:1,score:78,prog:35},{s:2,k:6,v:5,p:2,score:84,prog:50},{s:3,k:8,v:5,p:2,score:72,prog:68},{s:4,k:0,v:0,p:0,score:0,prog:0},{s:5,k:0,v:0,p:0,score:0,prog:0},{s:6,k:0,v:0,p:0,score:0,prog:0},{s:7,k:0,v:0,p:0,score:0,prog:0},{s:8,k:0,v:0,p:0,score:0,prog:0}];box.innerHTML=a.map(x=>`<tr><td>Semester ${x.s}</td><td>${x.k}</td><td>${x.v}</td><td>${x.p}</td><td>${x.score?x.score+'%':'Not available'}</td><td>${x.prog}%</td></tr>`).join('')}
function dashboard(){const skills=DB.get('skills',defaultSkills),projects=DB.get('projects',defaultProjects);[['#totalSkills',skills.length],['#verifiedSkills',skills.filter(x=>x.status==='Verified').length],['#inProgress',skills.filter(x=>x.status!=='Verified').length],['#projects',projects.length],['#semester',3],['#overall','68%']].forEach(([q,v])=>{const e=document.querySelector(q);if(e)e.textContent=v})}
function resume(){const p=DB.get('profile',profile),skills=DB.get('skills',defaultSkills),projects=DB.get('projects',defaultProjects);document.querySelector('#rname').textContent=p.name;document.querySelector('#rcontact').textContent=`${p.email} | ${p.phone} | ${p.department}`;document.querySelector('#rskills').innerHTML=skills.filter(s=>s.status==='Verified').map(s=>`<li>${s.name} — ${s.level}</li>`).join('');document.querySelector('#rprojects').innerHTML=projects.map(x=>`<li><b>${x.title}</b> — ${x.tech}</li>`).join('')}
function printResume(){window.print()}
function verify(button){const row=button.closest('tr');row.querySelector('.status').innerHTML='<span class="badge success">Verified</span>';button.disabled=true;toast('Evidence verified')}
function reject(button){const reason=prompt('Enter rejection reason:');if(reason){button.closest('tr').querySelector('.status').innerHTML='<span class="badge danger">Rejected</span>';toast('Evidence rejected')}}
document.addEventListener('DOMContentLoaded',()=>{init();dashboard();skillsPage();projectsPage();profilePage();semesterPage();resume()});
